package index

import (
	"database/sql"
	"errors"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/ahaley/markroom/internal/config"
)

func testStore(t *testing.T) *Store {
	t.Helper()
	s, err := Open(filepath.Join(t.TempDir(), "test.db"))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { s.Close() })
	return s
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestScanRootLifecycle(t *testing.T) {
	store := testStore(t)
	dir := t.TempDir()
	root := config.Root{Name: "test", Path: dir}

	writeFile(t, filepath.Join(dir, "a.md"), "# Title A\n\nhello world from doc a")
	writeFile(t, filepath.Join(dir, "sub", "b.md"), "no heading here")
	writeFile(t, filepath.Join(dir, "node_modules", "skip.md"), "# Skipped")
	writeFile(t, filepath.Join(dir, ".hidden", "skip.md"), "# Skipped")
	writeFile(t, filepath.Join(dir, "not-markdown.txt"), "plain text")

	n, err := store.ScanRoot(t.Context(), root)
	if err != nil {
		t.Fatal(err)
	}
	if n != 2 {
		t.Fatalf("indexed %d docs, want 2", n)
	}

	docs, err := store.ListDocs(t.Context(), "")
	if err != nil {
		t.Fatal(err)
	}
	if len(docs) != 2 {
		t.Fatalf("ListDocs returned %d, want 2", len(docs))
	}
	for _, d := range docs {
		if d.Status != "new" {
			t.Errorf("%s status = %q, want new", d.RelPath, d.Status)
		}
	}

	a, err := store.GetDoc(t.Context(), "test", "a.md")
	if err != nil {
		t.Fatal(err)
	}
	if a.Title != "Title A" {
		t.Errorf("title = %q, want Title A", a.Title)
	}
	b, err := store.GetDoc(t.Context(), "test", "sub/b.md")
	if err != nil {
		t.Fatal(err)
	}
	if b.Title != "b" {
		t.Errorf("headingless title = %q, want filename fallback b", b.Title)
	}

	// Reading pins the current hash.
	if err := store.MarkRead(t.Context(), a.ID, a.Hash); err != nil {
		t.Fatal(err)
	}
	a, _ = store.GetDoc(t.Context(), "test", "a.md")
	if a.Status != "read" {
		t.Fatalf("after MarkRead status = %q, want read", a.Status)
	}

	// Regeneration flips a read doc to "updated".
	writeFile(t, filepath.Join(dir, "a.md"), "# Title A\n\nregenerated by an agent")
	future := time.Now().Add(time.Hour)
	if err := os.Chtimes(filepath.Join(dir, "a.md"), future, future); err != nil {
		t.Fatal(err)
	}
	if _, err := store.ScanRoot(t.Context(), root); err != nil {
		t.Fatal(err)
	}
	a, _ = store.GetDoc(t.Context(), "test", "a.md")
	if a.Status != "updated" {
		t.Fatalf("after regeneration status = %q, want updated", a.Status)
	}

	// MarkUnread clears read state entirely.
	if err := store.MarkUnread(t.Context(), a.ID); err != nil {
		t.Fatal(err)
	}
	a, _ = store.GetDoc(t.Context(), "test", "a.md")
	if a.Status != "new" {
		t.Fatalf("after MarkUnread status = %q, want new", a.Status)
	}

	// Deleted files leave the index.
	if err := os.Remove(filepath.Join(dir, "sub", "b.md")); err != nil {
		t.Fatal(err)
	}
	n, err = store.ScanRoot(t.Context(), root)
	if err != nil {
		t.Fatal(err)
	}
	if n != 1 {
		t.Fatalf("after delete indexed %d, want 1", n)
	}
	if _, err := store.GetDoc(t.Context(), "test", "sub/b.md"); !errors.Is(err, sql.ErrNoRows) {
		t.Fatalf("deleted doc still present, err = %v", err)
	}

	total, unread, err := store.RootStats(t.Context(), "test")
	if err != nil {
		t.Fatal(err)
	}
	if total != 1 || unread != 1 {
		t.Fatalf("RootStats = (%d, %d), want (1, 1)", total, unread)
	}
}

func TestSearch(t *testing.T) {
	store := testStore(t)
	now := time.Now()
	must := func(err error) {
		t.Helper()
		if err != nil {
			t.Fatal(err)
		}
	}
	must(store.UpsertDoc(t.Context(), "r", "auth.md", []byte("# Auth Audit\n\nthe token refresh races"), now, 10))
	must(store.UpsertDoc(t.Context(), "r", "pay.md", []byte("# Payments\n\nledger reconciliation notes"), now, 10))

	docs, err := store.Search(t.Context(), "token", "")
	must(err)
	if len(docs) != 1 || docs[0].RelPath != "auth.md" {
		t.Fatalf("search token = %+v, want auth.md only", docs)
	}
	if docs[0].Snippet == "" {
		t.Error("expected a non-empty snippet")
	}

	// Prefix match: partial words hit.
	docs, err = store.Search(t.Context(), "reconcil", "")
	must(err)
	if len(docs) != 1 || docs[0].RelPath != "pay.md" {
		t.Fatalf("prefix search = %+v, want pay.md only", docs)
	}

	// Hostile input must not break the FTS query.
	for _, q := range []string{`"unbalanced`, `a" OR "b`, `NEAR( -- )`, `*`} {
		if _, err := store.Search(t.Context(), q, ""); err != nil {
			t.Errorf("search %q errored: %v", q, err)
		}
	}

	docs, err = store.Search(t.Context(), "nomatchword", "")
	must(err)
	if len(docs) != 0 {
		t.Fatalf("expected no results, got %d", len(docs))
	}
}

func TestRootFiltering(t *testing.T) {
	store := testStore(t)
	now := time.Now()
	must := func(err error) {
		t.Helper()
		if err != nil {
			t.Fatal(err)
		}
	}
	must(store.UpsertDoc(t.Context(), "r1", "a.md", []byte("# A\n\nshared alpha"), now, 10))
	must(store.UpsertDoc(t.Context(), "r1", "b.md", []byte("# B\n\nshared beta"), now, 10))
	must(store.UpsertDoc(t.Context(), "r2", "c.md", []byte("# C\n\nshared gamma"), now, 10))

	docs, err := store.ListDocs(t.Context(), "")
	must(err)
	if len(docs) != 3 {
		t.Fatalf("unfiltered ListDocs = %d docs, want 3", len(docs))
	}
	docs, err = store.ListDocs(t.Context(), "r1")
	must(err)
	if len(docs) != 2 {
		t.Fatalf("ListDocs r1 = %d docs, want 2", len(docs))
	}
	for _, d := range docs {
		if d.Root != "r1" {
			t.Errorf("ListDocs r1 returned doc from %q", d.Root)
		}
	}
	docs, err = store.ListDocs(t.Context(), "nope")
	must(err)
	if len(docs) != 0 {
		t.Fatalf("ListDocs nope = %d docs, want 0", len(docs))
	}

	docs, err = store.Search(t.Context(), "shared", "")
	must(err)
	if len(docs) != 3 {
		t.Fatalf("unscoped search = %d docs, want 3", len(docs))
	}
	docs, err = store.Search(t.Context(), "shared", "r2")
	must(err)
	if len(docs) != 1 || docs[0].RelPath != "c.md" {
		t.Fatalf("scoped search = %+v, want c.md only", docs)
	}
	if docs[0].Snippet == "" {
		t.Error("expected a non-empty snippet in scoped search")
	}

	counts, err := store.AllRootStats(t.Context())
	must(err)
	if c := counts["r1"]; c.Total != 2 || c.Unread != 2 {
		t.Fatalf("r1 stats = %+v, want {2 2}", c)
	}
	if c := counts["r2"]; c.Total != 1 || c.Unread != 1 {
		t.Fatalf("r2 stats = %+v, want {1 1}", c)
	}

	doc, err := store.GetDoc(t.Context(), "r1", "a.md")
	must(err)
	must(store.MarkRead(t.Context(), doc.ID, doc.Hash))
	counts, err = store.AllRootStats(t.Context())
	must(err)
	if c := counts["r1"]; c.Total != 2 || c.Unread != 1 {
		t.Fatalf("r1 stats after read = %+v, want {2 1}", c)
	}
}

func TestStripFrontmatter(t *testing.T) {
	tests := []struct{ name, in, want string }{
		{"none", "# Title\nbody", "# Title\nbody"},
		{"basic", "---\nauthor: agent\n---\n# Title\nbody", "# Title\nbody"},
		{"no trailing newline", "---\na: b\n---", ""},
		{"unterminated", "---\na: b\nnever closed", "---\na: b\nnever closed"},
		{"thematic break is not frontmatter", "----\nbody", "----\nbody"},
		{"empty", "", ""},
	}
	for _, tt := range tests {
		if got := StripFrontmatter(tt.in); got != tt.want {
			t.Errorf("%s: StripFrontmatter(%q) = %q, want %q", tt.name, tt.in, got, tt.want)
		}
	}
}

func TestExtractTitle(t *testing.T) {
	tests := []struct{ name, body, rel, want string }{
		{"h1", "# My Doc\n\nbody", "x.md", "My Doc"},
		{"h1 after blank lines", "\n\n# Later Heading\n", "x.md", "Later Heading"},
		{"trailing hashes trimmed", "# Closed ATX ##\n", "x.md", "Closed ATX"},
		{"h2 is not a title", "## Section\n", "notes.md", "notes"},
		{"fallback to filename", "plain text", "specs/payments.md", "payments"},
		{"empty h1 falls through", "# \n# Real Title\n", "x.md", "Real Title"},
	}
	for _, tt := range tests {
		if got := extractTitle(tt.body, tt.rel); got != tt.want {
			t.Errorf("%s: extractTitle = %q, want %q", tt.name, got, tt.want)
		}
	}
}

func TestIsMarkdown(t *testing.T) {
	for name, want := range map[string]bool{
		"a.md": true, "B.MD": true, "c.markdown": true,
		"d.txt": false, "md": false, "e.md.bak": false,
	} {
		if got := IsMarkdown(name); got != want {
			t.Errorf("IsMarkdown(%q) = %v, want %v", name, got, want)
		}
	}
}
